### PR TITLE
Set colour/mode to device default on reset

### LINKED ISSUE #34: Clicking reset clears the colour field
This is a pretty minor issue, but slightly annoying because the preview and scan buttons do not work until I select a color.  I think that clicking reset should default colour back to the first item in the list instead of clearing it.  When I first open the webpage, I have three color options (lineart, gray, and color) and lineart is selected.

### PR DESCRIPTION
**Pull request by JnCrMx**
Before it simply cleared the selected item in the combo box which prevented preview from working until a new item was selected.

This fixes #34

I'm unsure about ``this.render();``. It works, but there might be a better solution.

### CODE REVIEW

File: src/client.js [hunk 1]
```diff
@@ -111,8 +111,10 @@ $(document).ready(function () {
         reset: function () {
             var defaults = this.model.defaults();
             this.model.set(defaults);
+            this.model.attributes.mode = this.device.attributes.features['--mode'].default; // Set colour/mode to device default
```
Comment (sbs20) [inline src/client.js:114]: Your suspicion that there's a slightly better way was correct.

I think, ultimately the best way would be to change `ScanRequest.defaults()` to use the Device (if it's there - it may not be on page load) - but the way the code is structured would make that a bit more painful right now.

In the mean time, if you do this:
```
defaults.mode = this.device.attributes.features['--mode'].default;
```
... just after we get `defaults` and before `this.model.set(defaults)` then Backbone `model.set` will take care of rendering for you and you don't need `this.render` any more.

Comment (JnCrMx) [reply src/client.js:114]: I agree that changing the ``defaults()`` would be the best option, but it seems like Backbone doesn't *really* support changing them after extending/creating the Model.

It seems to be possible tho to just override the ``defaults()`` function in ``deviceSync``:

```js
this.model.defaults = function() {
    return {
        // LocalStorage requires an id in order to
        // update / read. This can be fixed to anything
        id: 0,
        top: 0,
        left: 0,
        width: 215,
        height: 297,
        resolution: 150,
        mode: device.attributes.features['--mode'].default,
        brightness: 0,
        contrast: 0,
        convertFormat: 'tif',
        dynamicLineart: true,
        multiplePages: false
    };
};
```

But I'm even more unsure about this solution because it also doesn't seem to be very good.

Comment (sbs20) [reply src/client.js:114]: Yeah, I think I'm with you in terms of being unsure. I suspect the cleanest way might be to change within the `default()` itself but if doesn't have access to `this.device`.

I say, for the time being go with the:

```javascript
defaults.mode = this.device.attributes.features['--mode'].default;
```

At least it's contained to one line of code for the time being. If we need to do more later with other defaults then perhaps we revisit. What do you think?

Comment (JnCrMx) [reply src/client.js:114]: Yeah, I think for now that is the best solution.
Should I just do another commit and add it to the pull request (if that's even possible) or rather remove the current commit from history, make and commit the change, and open a new pull request?

Comment (sbs20) [reply src/client.js:114]: Just do another commit and push. (My personal view is not to remove commits unless something has gone really horribly wrong!). It should automatically update into this PR.
